# Generated by Django 6.0.1 on 2026-01-17 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=122)),
                ('display_name', models.CharField(max_length=122)),
                ('avatar', models.CharField(max_length=122)),
                ('age', models.CharField(max_length=122)),
                ('gender', models.CharField(max_length=122)),
                ('preference', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=12)),
            ],
        ),
    ]
