# Generated by Django 6.0.1 on 2026-01-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hush_points',
            field=models.CharField(default=0, max_length=12),
            preserve_default=False,
        ),
    ]
