# Generated by Django 6.0.1 on 2026-01-20 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gift',
            name='sender',
        ),
    ]
