# Generated by Django 6.0.1 on 2026-01-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_profile_message_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='icon',
            field=models.CharField(blank=True, default='👥', max_length=10),
        ),
    ]
